### ISSUE TITLE
Invalid Credentials Using production Data

### ISSUE THREAD

**Issue by luizfelipetx** [mercadopago/sdk-android#13]
Hi, 
im getting some problems in integration with android sdk, i have total success using TEST keys , public and secret, but when i tried change to production keys no work. I open the code from sdk too , and create some logs. With TEST Keys ok , With production Keys this is the message directly from Server : 

`05-04 23:03:10.884 29614-29614/com.mercadopago.example D/EXCEPION: {"message":"Invalid credentials","cause":[{"description":"Invalid credentials","data":null,"code":17}],"error":"bad_request","status":400}---Bad Request
`

So, I have a configured account in Mercado Pago. I create a new project to share here the keys. This Key and this account no have any money, or charged values, i just create to test. I will regenerate this keys after solve the problem. In FAQ or stackoverflow anyone had this problem. My Country is Brazil (BRL) 

Thanks

**Comment by sebagun** [comment]
Never publish your credentials! Never mind if the account doesn't have money, you're putting your account in serious danger right now. Please edit or delete this issue and give detailed information about it, without making public your account details.

**Comment by luizfelipetx** [comment]
Done!, 
So , my blank account, can you help ?

**Comment by luizfelipetx** [comment]
My account is created just to test, as i say in first text, and no problem to me to share ,  but anyway..

This is, It is a known issue ?

**Comment by scirielli** [comment]
Hi,
the problem is that you're using your productive credentials on the examples mock server (this is a test-only server).
To run your production environment you have to replace the test end-point (https://www.mercadopago.com/checkout/examples/doPayment) with YOUR OWN payment creation end-point. 
You can find a PHP server example of how to do that here:
https://github.com/mercadopago/customcheckout-php-server

Regards,
SC

**Comment by luizfelipetx** [comment]
Thanks.

**Comment by Brunoandroid** [comment]
ola alguem pode mim dar uma ajuda?
